# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FirebaseTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Core'

  # Pods for FirebaseTest

  target 'FirebaseTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
